name: Build Status
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - run: |
          git remote set-url origin git@github.com:KryNak/japan-ticket-price.git
      - name: reveal
        uses: entrostat/git-secret-action@v4
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-private-key-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17.0.4'
      - if: ${{ !env.ACT }}
        name: release
        run: ./gradlew release
      - run: echo ${{ steps.release.outputs.released-version }}
      - if: ${{ env.ACT }}
        run: |
          set +e
          (test "$(git config remote.origin.url)" = "git@github.com:KryNak/japan-ticket-price.git" \
          && echo "remote.origin.url is set ok" || echo "remote.origin.url is wrongly set") \
          && ./gradlew release -Prelease.localOnly
